/**
 * Additional changes © 2025 Closify.
 * Original source: Meta Platforms, Inc. and affiliates.
 * Modifications licensed under the same terms below.
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * You are hereby granted a non-exclusive, worldwide, royalty-free license to use,
 * copy, modify, and distribute this software in source code or binary form for use
 * in connection with the web services and APIs provided by Facebook.
 *
 * As with any software that integrates with the Facebook platform, your use of
 * this software is subject to the Facebook Platform Policy
 * [http://developers.facebook.com/policy/]. This copyright notice shall be
 * included in all copies or substantial portions of the software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

// #region Media Types

export enum AudioMediaTypesEnum {
  Aac = 'audio/aac',
  Amr = 'audio/amr',
  Mp4 = 'audio/mp4',
  Mpeg = 'audio/mpeg',
  Ogg = 'audio/ogg',
}

export enum DocumentMediaTypesEnum {
  Excel = 'application/vnd.ms-excel',
  OpenDoc = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  OpenPres = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  OpenSheet = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  Pdf = 'application/pdf',
  Ppt = 'application/vnd.ms-powerpoint',
  Text = 'text/plain',
  Word = 'application/msword',
}

export enum ImageMediaTypesEnum {
  Jpeg = 'image/jpeg',
  Png = 'image/png',
}

export enum StickerMediaTypesEnum {
  Webp = 'image/webp',
}

export enum VideoMediaTypesEnum {
  Mp4 = 'video/mp4',
  Threegp = 'video/3gp',
}

// #endregion

// #region Template Message Types

export enum TemplateCategoryEnum {
  Authentication = 'AUTHENTICATION',
  Marketing = 'MARKETING',
  Utility = "UTILITY"
}

export enum TemplateIndustryEnum {
  ECommerce = 'ECOMMERCE',
  FinancialServices = 'FINANCIAL_SERVICES',
  Hospitality = 'HOSPITALITY',
}

export enum TemplateLibraryParameterEnum {
  Address = 'ADDRESS',
  Amount = 'AMOUNT',
  Date = 'DATE',
  Email = 'EMAIL',
  Number = 'NUMBER',
  PhoneNumber = 'PHONE_NUMBER',
  Text = 'TEXT',
}

export enum TemplateStatusEnum {
  Approved = 'APPROVED',
  Pending = 'PENDING',
  Rejected = 'REJECTED',
}

export enum TemplateTopicEnum {
  AccountUpdate = 'ACCOUNT_UPDATE',
  CustomerFeedback = 'CUSTOMER_FEEDBACK',
  OrderManagement = 'ORDER_MANAGEMENT',
  Payments = 'PAYMENTS',
}

export enum TemplateUseCaseEnum {
  AccountCreationInformation = 'ACCOUNT_CREATION_INFORMATION',
  AutoPayReminder = 'AUTO_PAY_REMINDER',
  DeliveryConfirmation = 'DELIVERY_CONFIRMATION',
  DeliveryFailed = 'DELIVERY_FAILED',
  DeliveryUpdate = 'DELIVERY_UPDATE',
  FeedbackSurvey = 'FEEDBACK_SURVEY',
  FraudAlert = 'FRAUD_ALERT',
  LowBalanceWarning = 'LOW_BALANCE_WARNING',
  OrderActionNeeded = 'ORDER_ACTION_NEEDED',
  OrderConfirmation = 'ORDER_CONFIRMATION',
  OrderDelay = 'ORDER_DELAY',
  OrderOrTransactionCancel = 'ORDER_OR_TRANSACTION_CANCEL',
  OrderPickUp = 'ORDER_PICK_UP',
  PaymentActionRequired = 'PAYMENT_ACTION_REQUIRED',
  PaymentConfirmation = 'PAYMENT_CONFIRMATION',
  PaymentDueReminder = 'PAYMENT_DUE_REMINDER',
  PaymentOverdue = 'PAYMENT_OVERDUE',
  PaymentRejectFail = 'PAYMENT_REJECT_FAIL',
  PaymentScheduled = 'PAYMENT_SCHEDULED',
  ReceiptAtttachment = 'RECEIPT_ATTACHMENT',
  ReturnConfirmation = 'RETURN_CONFIRMATION',
  ShipmentConfirmation = 'SHIPMENT_CONFIRMATION',
  StatementAttachment = 'STATEMENT_ATTACHMENT',
  StatementAvailable = 'STATEMENT_AVAILABLE',
  TransactionAlert = 'TRANSACTION_ALERT',
}

// #endregion

export enum ButtonPositionEnum {
  First,
  Second,
  Third,
}

export enum ButtonTypesEnum {
  Catalog = 'catalog',
  CopyCode = 'copy_code',
  Flow = 'flow',
  QuickReply = 'quick_reply',
  MultiProduct = 'mpm',
  URL = 'url',
}

export enum ComponentTypesEnum {
  Body = 'body',
  Button = 'button',
  Buttons = 'buttons',
  Carousel = 'carousel',
  Header = 'header',
  LimitedTimeOffer = 'limited_time_offer',
  TapTarget = 'tap_target_configuration',
}

export enum ConversationCategoryEnum {
  Authentication = 'authentication',
  AuthenticationInternational = 'authentication_international',
  Marketing = 'marketing',
  MarketingLite = 'marketing_lite',
  ReferralConversion = 'referral_conversion',
  Service = 'service',
  Utility = 'utility',
}

export enum ConversationTypesEnum {
  BusinessInitiated = 'business_initiated',
  CustomerInitiated = 'customer_initiated',
  ReferralConversion = 'referral_conversion',
}

export enum CurrencyCodesEnum {
  ADP = 'ADP',
  AED = 'AED',
  AFA = 'AFA',
  AFN = 'AFN',
  ALK = 'ALK',
  ALL = 'ALL',
  AMD = 'AMD',
  ANG = 'ANG',
  AOA = 'AOA',
  AOK = 'AOK',
  AON = 'AON',
  AOR = 'AOR',
  ARA = 'ARA',
  ARP = 'ARP',
  ARS = 'ARS',
  ARY = 'ARY',
  ATS = 'ATS',
  AUD = 'AUD',
  AWG = 'AWG',
  AYM = 'AYM',
  AZM = 'AZM',
  AZN = 'AZN',
  BAD = 'BAD',
  BAM = 'BAM',
  BBD = 'BBD',
  BDT = 'BDT',
  BEC = 'BEC',
  BEF = 'BEF',
  BEL = 'BEL',
  BGJ = 'BGJ',
  BGK = 'BGK',
  BGL = 'BGL',
  BGN = 'BGN',
  BHD = 'BHD',
  BIF = 'BIF',
  BMD = 'BMD',
  BND = 'BND',
  BOB = 'BOB',
  BOP = 'BOP',
  BOV = 'BOV',
  BRB = 'BRB',
  BRC = 'BRC',
  BRE = 'BRE',
  BRL = 'BRL',
  BRN = 'BRN',
  BRR = 'BRR',
  BSD = 'BSD',
  BTN = 'BTN',
  BUK = 'BUK',
  BWP = 'BWP',
  BYB = 'BYB',
  BYN = 'BYN',
  BYR = 'BYR',
  BZD = 'BZD',
  CAD = 'CAD',
  CDF = 'CDF',
  CHC = 'CHC',
  CHE = 'CHE',
  CHF = 'CHF',
  CHW = 'CHW',
  CLF = 'CLF',
  CLP = 'CLP',
  CNY = 'CNY',
  COP = 'COP',
  COU = 'COU',
  CRC = 'CRC',
  CSD = 'CSD',
  CSJ = 'CSJ',
  CSK = 'CSK',
  CUC = 'CUC',
  CUP = 'CUP',
  CVE = 'CVE',
  CYP = 'CYP',
  CZK = 'CZK',
  DDM = 'DDM',
  DEM = 'DEM',
  DJF = 'DJF',
  DKK = 'DKK',
  DOP = 'DOP',
  DZD = 'DZD',
  ECS = 'ECS',
  ECV = 'ECV',
  EEK = 'EEK',
  EGP = 'EGP',
  ERN = 'ERN',
  ESA = 'ESA',
  ESB = 'ESB',
  ESP = 'ESP',
  ETB = 'ETB',
  EUR = 'EUR',
  FIM = 'FIM',
  FJD = 'FJD',
  FKP = 'FKP',
  FRF = 'FRF',
  GBP = 'GBP',
  GEK = 'GEK',
  GEL = 'GEL',
  GHC = 'GHC',
  GHP = 'GHP',
  GHS = 'GHS',
  GIP = 'GIP',
  GMD = 'GMD',
  GNE = 'GNE',
  GNF = 'GNF',
  GNS = 'GNS',
  GQE = 'GQE',
  GRD = 'GRD',
  GTQ = 'GTQ',
  GWE = 'GWE',
  GWP = 'GWP',
  GYD = 'GYD',
  HKD = 'HKD',
  HNL = 'HNL',
  HRD = 'HRD',
  HRK = 'HRK',
  HTG = 'HTG',
  HUF = 'HUF',
  IDR = 'IDR',
  IEP = 'IEP',
  ILP = 'ILP',
  ILR = 'ILR',
  ILS = 'ILS',
  INR = 'INR',
  IQD = 'IQD',
  IRR = 'IRR',
  ISJ = 'ISJ',
  ISK = 'ISK',
  ITL = 'ITL',
  JMD = 'JMD',
  JOD = 'JOD',
  JPY = 'JPY',
  KES = 'KES',
  KGS = 'KGS',
  KHR = 'KHR',
  KMF = 'KMF',
  KPW = 'KPW',
  KRW = 'KRW',
  KWD = 'KWD',
  KYD = 'KYD',
  KZT = 'KZT',
  LAJ = 'LAJ',
  LAK = 'LAK',
  LBP = 'LBP',
  LKR = 'LKR',
  LRD = 'LRD',
  LSL = 'LSL',
  LSM = 'LSM',
  LTL = 'LTL',
  LTT = 'LTT',
  LUC = 'LUC',
  LUF = 'LUF',
  LUL = 'LUL',
  LVL = 'LVL',
  LVR = 'LVR',
  LYD = 'LYD',
  MAD = 'MAD',
  MDL = 'MDL',
  MGA = 'MGA',
  MGF = 'MGF',
  MKD = 'MKD',
  MLF = 'MLF',
  MMK = 'MMK',
  MNT = 'MNT',
  MOP = 'MOP',
  MRO = 'MRO',
  MRU = 'MRU',
  MTL = 'MTL',
  MTP = 'MTP',
  MUR = 'MUR',
  MVQ = 'MVQ',
  MVR = 'MVR',
  MWK = 'MWK',
  MXN = 'MXN',
  MXP = 'MXP',
  MXV = 'MXV',
  MYR = 'MYR',
  MZE = 'MZE',
  MZM = 'MZM',
  MZN = 'MZN',
  NAD = 'NAD',
  NGN = 'NGN',
  NIC = 'NIC',
  NIO = 'NIO',
  NLG = 'NLG',
  NOK = 'NOK',
  NPR = 'NPR',
  NZD = 'NZD',
  OMR = 'OMR',
  PAB = 'PAB',
  PEH = 'PEH',
  PEI = 'PEI',
  PEN = 'PEN',
  PES = 'PES',
  PGK = 'PGK',
  PHP = 'PHP',
  PKR = 'PKR',
  PLN = 'PLN',
  PLZ = 'PLZ',
  PTE = 'PTE',
  PYG = 'PYG',
  QAR = 'QAR',
  RHD = 'RHD',
  ROK = 'ROK',
  ROL = 'ROL',
  RON = 'RON',
  RSD = 'RSD',
  RUB = 'RUB',
  RUR = 'RUR',
  RWF = 'RWF',
  SAR = 'SAR',
  SBD = 'SBD',
  SCR = 'SCR',
  SDD = 'SDD',
  SDG = 'SDG',
  SDP = 'SDP',
  SEK = 'SEK',
  SGD = 'SGD',
  SHP = 'SHP',
  SIT = 'SIT',
  SKK = 'SKK',
  SLL = 'SLL',
  SOS = 'SOS',
  SRD = 'SRD',
  SRG = 'SRG',
  SSP = 'SSP',
  STD = 'STD',
  STN = 'STN',
  SUR = 'SUR',
  SVC = 'SVC',
  SYP = 'SYP',
  SZL = 'SZL',
  THB = 'THB',
  TJR = 'TJR',
  TJS = 'TJS',
  TMM = 'TMM',
  TMT = 'TMT',
  TND = 'TND',
  TOP = 'TOP',
  TPE = 'TPE',
  TRL = 'TRL',
  TRY = 'TRY',
  TTD = 'TTD',
  TWD = 'TWD',
  TZS = 'TZS',
  UAH = 'UAH',
  UAK = 'UAK',
  UGS = 'UGS',
  UGW = 'UGW',
  UGX = 'UGX',
  USD = 'USD',
  USN = 'USN',
  USS = 'USS',
  UYI = 'UYI',
  UYN = 'UYN',
  UYP = 'UYP',
  UYU = 'UYU',
  UYW = 'UYW',
  UZS = 'UZS',
  VEB = 'VEB',
  VEF = 'VEF',
  VES = 'VES',
  VNC = 'VNC',
  VND = 'VND',
  VUV = 'VUV',
  WST = 'WST',
  XAF = 'XAF',
  XAG = 'XAG',
  XAU = 'XAU',
  XBA = 'XBA',
  XBB = 'XBB',
  XBC = 'XBC',
  XBD = 'XBD',
  XCD = 'XCD',
  XDR = 'XDR',
  XEU = 'XEU',
  XFO = 'XFO',
  XFU = 'XFU',
  XOF = 'XOF',
  XPD = 'XPD',
  XPF = 'XPF',
  XPT = 'XPT',
  XRE = 'XRE',
  XSU = 'XSU',
  XTS = 'XTS',
  XUA = 'XUA',
  XXX = 'XXX',
  YDD = 'YDD',
  YER = 'YER',
  YUD = 'YUD',
  YUM = 'YUM',
  YUN = 'YUN',
  ZAL = 'ZAL',
  ZAR = 'ZAR',
  ZMK = 'ZMK',
  ZMW = 'ZMW',
  ZRN = 'ZRN',
  ZRZ = 'ZRZ',
  ZWC = 'ZWC',
  ZWD = 'ZWD',
  ZWL = 'ZWL',
  ZWN = 'ZWN',
  ZWR = 'ZWR',
}

export enum HttpMethodsEnum {
  Delete = 'DELETE',
  Get = 'GET',
  Post = 'POST',
  Put = 'PUT',
}

export enum InteractiveTypesEnum {
  Address = 'address_message',
  Button = 'button',
  CallToAction = 'cta_url',
  Flow = 'flow',
  List = 'list',
  LocationRequest = 'location_request_message',
  Product = 'product',
  ProductList = 'product_list',
}

export enum LanguagesEnum {
  Afrikaans = 'af',
  Albanian = 'sq',
  Arabic = 'ar',
  Azerbaijani = 'az',
  Bengali = 'bn',
  Bulgarian = 'bg',
  Catalan = 'ca',
  Chinese_CHN = 'zh_CN',
  Chinese_HKG = 'zh_HK',
  Chinese_TAI = 'zh_TW',
  Croatian = 'hr',
  Czech = 'cs',
  Danish = 'da',
  Dutch = 'nl',
  English = 'en',
  English_UK = 'en_GB',
  English_US = 'en_US',
  Estonian = 'et',
  Filipino = 'fil',
  Finnish = 'fi',
  French = 'fr',
  Georgian = 'ka',
  German = 'de',
  Greek = 'el',
  Gujarati = 'gu',
  Hausa = 'ha',
  Hebrew = 'he',
  Hindi = 'hi',
  Hungarian = 'hu',
  Indonesian = 'id',
  Irish = 'ga',
  Italian = 'it',
  Japanese = 'ja',
  Kannada = 'kn',
  Kazakh = 'kk',
  Kinyarwanda = 'rw_RW',
  Korean = 'ko',
  Kyrgyz_Kyrgyzstan = 'ky_KG',
  Lao = 'lo',
  Latvian = 'lv',
  Lithuanian = 'lt',
  Macedonian = 'mk',
  Malay = 'ms',
  Malayalam = 'ml',
  Marathi = 'mr',
  Norwegian = 'nb',
  Persian = 'fa',
  Polish = 'pl',
  Portuguese_BR = 'pt_BR',
  Portuguese_POR = 'pt_PT',
  Punjabi = 'pa',
  Romanian = 'ro',
  Russian = 'ru',
  Serbian = 'sr',
  Slovak = 'sk',
  Slovenian = 'sl',
  Spanish = 'es',
  Spanish_ARG = 'es_AR',
  Spanish_MEX = 'es_MX',
  Spanish_SPA = 'es_ES',
  Swahili = 'sw',
  Swedish = 'sv',
  Tamil = 'ta',
  Telugu = 'te',
  Thai = 'th',
  Turkish = 'tr',
  Ukrainian = 'uk',
  Urdu = 'ur',
  Uzbek = 'uz',
  Vietnamese = 'vi',
  Zulu = 'zu',
}

export enum MessageTypesEnum {
  Audio = 'audio', // for audio messages.
  Contacts = 'contacts', // for contact messages.
  Document = 'document', // for document messages.
  Image = 'image', // for image messages.
  Interactive = 'interactive', // for list and reply button messages.
  Location = 'location', // for location messages.
  Reaction = 'reaction', // for reaction messages.
  Sticker = 'sticker', // for sticker messages.
  Template = 'template', // for template messages. Text and media (images and documents) message templates are supported.
  Text = 'text', // for text messages.
  Video = 'video', // for video messages
}

export enum ParameterTypesEnum {
  Action = 'action',
  CouponCode = 'coupon_code',
  Currency = 'currency',
  DateTime = 'date_time',
  Document = 'document',
  Flow = 'flow',
  Image = 'image',
  LimitedTimeOffer = 'limited_time_offer',
  Location = 'location',
  Payload = 'payload',
  Product = 'product',
  TapTarget = 'tap_target_configuration',
  Text = 'text',
  Video = 'video',
}

export enum PricingTypeEnum {
  FreeCustomerService = 'free_customer_service',
  FreeEntryPoint = 'free_entry_point',
  Regular = 'regular',
}

export enum ReferralSourceTypesEnum {
  Ad = 'ad',
  Post = 'post',
}

export enum StatusEnum {
  Delivered = 'delivered',
  Failed = 'failed',
  Read = 'read',
  Sent = 'sent',
}

export enum SystemChangeTypesEnum {
  CustomerChangedNumber = 'customer_changed_number',
  CustomerIdentityChanged = 'customer_identity_changed',
}

export enum WAConfigEnum {
  AccessToken = 'CLOUD_API_ACCESS_TOKEN',
  APIVersion = 'CLOUD_API_VERSION',
  AppId = 'M4D_APP_ID',
  AppSecret = 'M4D_APP_SECRET',
  BaseURL = 'WA_BASE_URL',
  BusinessAcctId = 'WA_BUSINESS_ACCOUNT_ID',
  Debug = 'DEBUG',
  ListenerPort = 'LISTENER_PORT',
  MaxRetriesAfterWait = 'MAX_RETRIES_AFTER_WAIT',
  PhoneNumberId = 'WA_PHONE_NUMBER_ID',
  RequestTimeout = 'REQUEST_TIMEOUT',
  WebhookEndpoint = 'WEBHOOK_ENDPOINT',
  WebhookVerificationToken = 'WEBHOOK_VERIFICATION_TOKEN',
}

export enum WARequiredConfigEnum {
  AccessToken = 'CLOUD_API_ACCESS_TOKEN',
  APIVersion = 'CLOUD_API_VERSION',
}

export enum WebhookMessageTypesEnum {
  Audio = 'audio',
  Button = 'button',
  Document = 'document',
  Image = 'image',
  Interactive = 'interactive',
  Order = 'order',
  Sticker = 'sticker',
  System = 'system',
  Text = 'text',
  Unknown = 'unknown',
  Video = 'video',
}
